Prevent double-quote issues when packaging buildpacks

diff --git a/.github/workflows/_buildpacks-release.yml b/.github/workflows/_buildpacks-release.yml
--- a/.github/workflows/_buildpacks-release.yml
+++ b/.github/workflows/_buildpacks-release.yml
@@ -85,8 +85,10 @@ jobs:
         run: rustup update
 
       - name: Install cross-compile tooling
+        env:
+          TARGETS: ${{ steps.generate-buildpack-matrix.outputs.targets }}
         run: |
-          target_list=$(jq -c -r 'join(" ")' <<< '${{ steps.generate-buildpack-matrix.outputs.targets }}')
+          target_list=$(echo "$TARGETS" | jq -c -r 'join(" ")')
           read -a targets <<< "${target_list:-linux/amd64}"
           for target in "${targets[@]}"; do
             if [ "linux/arm64" = "${target}" ]; then
@@ -116,27 +118,30 @@ jobs:
 
       - name: Package buildpacks
         id: libcnb-package
+        env:
+          BUILDPACKS: ${{ steps.generate-buildpack-matrix.outputs.targets }}
         run: |
           package_dir=$(realpath "${{ env.PACKAGE_DIR }}")
-          echo '${{ steps.generate-buildpack-matrix.outputs.buildpacks }}' | jq -c '.[]' | while read buildpack; do
+          echo "$BUILDPACKS" | jq -c '.[]' | while read buildpack; do
             buildpack_dir=$(echo "${buildpack}" | jq -c -r '.buildpack_dir')
-            targets=$(echo "${buildpack}" | jq -c -r '.targets')
             cd "${buildpack_dir}"
             if [ -f "${buildpack_dir}/bin/build" ] && [ -f "${buildpack_dir}/bin/detect" ]; then
               echo "Skipping ${buildpack_dir}"
-            else
-              if [ "[]" = "${targets}" ]; then
-                cargo libcnb package --release --package-dir "${package_dir}"
-              else
-                echo "${targets}" | jq -c -r '.[]' | while read target; do
-                  if [ "linux/arm64" = "${target}" ]; then
-                    cargo libcnb package --release --package-dir "${package_dir}" --target aarch64-unknown-linux-musl
-                  elif [ "linux/amd64" = "${target}" ]; then
-                    cargo libcnb package --release --package-dir "${package_dir}" --target x86_64-unknown-linux-musl
-                  fi
-                done
-              fi
+              continue
             fi
+            target_list=$(echo "${buildpack}" | jq -c -r '.targets | join(" ")')
+            read -a targets <<< "${target_list:-linux/amd64}"
+            for target in targets; do
+                if [ "linux/amd64" = "${target}" ]; then
+                  rust_target="x86_64-unknown-linux-musl"
+                elif [ "linux/arm64" = "${target}" ]; then
+                  rust_target="aarch64-unknown-linux-musl"
+                else
+                  echo "ERROR: Unknown target: ${target}. Can't package buildpack."
+                  exit 1
+                fi
+                cargo libcnb package --release --package-dir "${package_dir}" --target "$rust_target"
+            done
           done
 
       - name: Generate changelog
